In [40]:
import pandas as pd
french = pd.read_csv("french.csv", encoding='utf-8')

In [41]:
french

symbol     jobno       dat language  \
0              A/46/2(SUPP)  N9325456  19930101   French   
1                 A/47/1000  N9344926  19930813   French   
2                 A/47/1001  N9345599  19930820   French   
3                 A/47/1004  N9346992  19930826   French   
4                 A/47/1008  N9348298  19930902   French   
5                 A/47/1010  N9348538  19930903   French   
6                 A/47/1015  N9349298  19930910   French   
7                 A/47/1019  N9350236  19930915   French   
8                 A/47/1020  N9350449  19930916   French   
9                 A/47/1021  N9350872  19930917   French   
10                A/47/1023  N9351563  19930923   French   
11                A/47/1024  N9351038  19930920   French   
12                   A/47/2  N9332437  19930602   French   
13                 A/47/883  N9307475  19930205   French   
14                 A/47/886  N9308030  19930209   French   
15                 A/47/891  N9309360  19930218   French   
16                 A/47/897  N9319254  19930402   French   
17                 A/47/906  N9314275  19930311   French   
18                 A/47/908  N9315857  19930323   French   
19                 A/47/909  N9316577  19930322   French   
20                 A/47/911  N9316904  19930322   French   
21                 A/47/913  N9317509  19930325   French   
22                 A/47/916  N9318645  19930331   French   
23                 A/47/919  N9319022  19930401   French   
24                 A/47/924  N9321197  19930412   French   
25                 A/47/925  N9321750  19930414   French   
26                 A/47/927  N9321974  19930415   French   
27                 A/47/928  N9322511  19930419   French   
28                 A/47/932  N9324388  19930428   French   
29                 A/47/935  N9324581  19930429   French   
...                     ...       ...       ...      ...   
28361       S/AC.55/2014/14  N1430128  20140415   French   
28362       S/AC.55/2014/15  N1430937  20140422   French   
28363       S/AC.55/2014/16  N1431386  20140425   French   
28364        S/AC.55/2014/2  N1427197  20140321   French   
28365        S/AC.55/2014/3  N1427277  20140320   French   
28366        S/AC.55/2014/4  N1427316  20140320   French   
28367        S/AC.55/2014/5  N1427484  20140305   French   
28368        S/AC.55/2014/6  N1427519  20140305   French   
28369        S/AC.55/2014/7  N1427685  20140324   French   
28370        S/AC.55/2014/8  N1427859  20140326   French   
28371        S/AC.55/2014/9  N1429193  20140407   French   
28372  S/AC.55/2014/1/ADD.1  N1429385  20140404   French   
28373  S/AC.55/2014/5/ADD.1  N1430943  20140423   French   
28374         S/PRST/2014/1  N1420492  20140110   French   
28375         S/PRST/2014/3  N1423339  20140212   French   
28376         S/PRST/2014/4  N1423620  20140214   French   
28377         S/PRST/2014/5  N1424278  20140221   French   
28378         S/PRST/2014/7  N1432405  20140507   French   
28379     S/RES/2134 (2014)  N1421895  20140128   French   
28380     S/RES/2135 (2014)  N1422175  20140130   French   
28381     S/RES/2139 (2014)  N1424340  20140222   French   
28382     S/RES/2140 (2014)  N1424708  20140226   French   
28383     S/RES/2141 (2014)  N1425364  20140305   French   
28384     S/RES/2145 (2014)  N1426684  20140316   French   
28385     S/RES/2148 (2014)  N1428955  20140403   French   
28386     S/RES/2149 (2014)  N1429582  20140410   French   
28387     S/RES/2151 (2014)  N1431392  20140428   French   
28388     S/RES/2152 (2014)  N1431482  20140429   French   
28389     S/RES/2153 (2014)  N1431494  20140429   French   
28390     S/RES/2154 (2014)  N1432859  20140508   French   

                                                keywords  \
0      ['HUMANITARIAN ASSISTANCE', 'LEBANON', 'CYPRUS...   
1      ['NEGOTIATION', 'POLITICAL CONDITIONS', 'HAITI...   
2      ['MAPS', 'PEACEKEEPING OPERATIONS', 'CYPRUS', ...   
3      ['PEACEKEEPING OPERATIONS', 'CYPRUS', 'FINANCI...   


In [16]:
data1 = frenchp[frenchp.Category == 'Assistance']
data1 = data1[1:1000]
data2 = frenchp[frenchp.Category == 'Consultations']
data2 = data2[1:1000]
data3 = frenchp[frenchp.Category == 'Disarment']
data3 = data3[1:1000]
data4 = frenchp[frenchp.Category == 'Negotiation']
data4 = data4[1:1000]
data5 = frenchp[frenchp.Category == 'Nuclear']
data5 = data5[1:1000]
data6 = frenchp[frenchp.Category == 'Peace']
data6 = data6[1:1000]
data7 = frenchp[frenchp.Category == 'Sanctions']
data7 = data7[1:1000]
data8 = frenchp[frenchp.Category == 'War']
data8 = data8[1:1000]

In [17]:
frames = [data1,data2,data3,data4,data5,data6,data7,data8]
frenchp = pd.concat(frames)

frenchp

symbol     jobno       dat language  \
12           A/47/2  N9332437  19930602   French   
13         A/47/883  N9307475  19930205   French   
14         A/47/886  N9308030  19930209   French   
38         A/47/965  N9335138  19930615   French   
39         A/47/967  N9336113  19930615   French   
43         A/47/977  N9340548  19930719   French   
46         A/47/981  N9341116  19930722   French   
56    A/47/12/ADD.1  N9318380  19930101   French   
57     A/47/3/REV.1  N9315784  19930318   French   
77          A/48/12  N9353417  19931006   French   
86         A/48/134  N9321132  19930412   French   
108          A/48/2  N9355948  19931019   French   
114        A/48/215  N9336356  19930621   French   
131          A/48/3  N9350224  19930915   French   
141        A/48/323  N9345611  19930924   French   
151        A/48/349  N9347205  19930827   French   
168        A/48/391  N9351548  19930923   French   
169        A/48/392  N9349321  19930922   French   
182        A/48/434  N9351831  19931006   French   
190        A/48/453  N9352651  19931006   French   
199        A/48/467  N9353786  19931022   French   
201        A/48/473  N9354034  19931008   French   
205        A/48/484  N9354827  19931018   French   
214        A/48/504  N9356489  19931029   French   
219        A/48/523  N9358080  19931025   French   
221        A/48/534  N9357737  19931022   French   
223        A/48/536  N9358074  19931104   French   
238        A/48/595  N9363079  19931112   French   
239        A/48/602  N9363536  19931115   French   
246        A/48/626  N9365809  19931124   French   
...             ...       ...       ...      ...   
6194     S/1996/288  N9609576  19960416   French   
6196      S/1996/29  N9600640  19960112   French   
6199     S/1996/299  N9609837  19960418   French   
6204     S/1996/309  N9610142  19960422   French   
6215     S/1996/330  N9611278  19960502   French   
6217     S/1996/334  N9611562  19960506   French   
6220     S/1996/337  N9611753  19960507   French   
6222      S/1996/34  N9600945  19960117   French   
6223     S/1996/341  N9611841  19960508   French   
6226     S/1996/347  N9612117  19960513   French   
6230     S/1996/359  N9612749  19960521   French   
6247     S/1996/386  N9613384  19960529   French   
6255     S/1996/403  N9613850  19960603   French   
6257     S/1996/410  N9614323  19960607   French   
6260     S/1996/413  N9614383  19960610   French   
6268     S/1996/429  N9614663  19960612   French   
6273     S/1996/438  N9615092  19960617   French   
6291     S/1996/471  N9615842  19960625   French   
6323     S/1996/527  N9616905  19960708   French   
6327     S/1996/536  N9617287  19960710   French   
6342     S/1996/561  N9617784  19960717   French   
6354     S/1996/584  N9618530  19960722   French   
6365     S/1996/602  N9619175  19960729   French   
6369     S/1996/610  N9619433  19960731   French   
6373     S/1996/617  N9619558  19960801   French   
6377     S/1996/625  N9619775  19960805   French   
6385     S/1996/642  N9620359  19960809   French   
6387     S/1996/645  N9620437  19960812   French   
6388     S/1996/646  N9620467  19960812   French   
6389     S/1996/657  N9620754  19960814   French   

                                               keywords  \
12    ['DISPUTES', 'LIBYA', 'UNITED STATES', 'BELIZE...   
13    ['HUMANITARIAN ASSISTANCE', 'BOSNIA AND HERZEG...   
14    ['AIRPORTS', 'SARAJEVO (BOSNIA AND HERZEGOVINA...   
38    ['PREVENTIVE DIPLOMACY', 'FACT-FINDING MISSION...   
39    ['PEACEKEEPING OPERATIONS', 'CROATIA', 'HUMANI...   
43    ['POLITICAL STATUS', 'JAMMU AND KASHMIR', 'CEA...   
46    ['HUMANITARIAN ASSISTANCE', 'PEACEKEEPING OPER...   
56    ['HUMANITARIAN ASSISTANCE', 'TREATIES', 'REFUG...   
57    ['ECONOMIC ASSISTANCE', 'HUMANITARIAN ASSISTAN...   
77    ['REFUGEE ASSISTANCE', 'AFRICA', 'NORTH AMERIC...   
86    ['CHILD REFUGEES', 'WOMEN REFUGEES', 'REFUGEES...   
108   ['BOUNDARIES', 'SPECIAL MISSIONS', 'IRAQ', 'KU...   
114   ['DEVELOPMENT A

In [7]:
data1 = frenchp[frenchp.Category == 'Assistance']
data1 = data1[0:10]
data2 = frenchp[frenchp.Category == 'Consultations']
data2 = data2[0:10]
data3 = frenchp[frenchp.Category == 'Disarment']
data3 = data3[0:10]
data4 = frenchp[frenchp.Category == 'Negotiation']
data4 = data4[0:10]
data5 = frenchp[frenchp.Category == 'Nuclear']
data5 = data5[0:10]
data6 = frenchp[frenchp.Category == 'Peace']
data6 = data6[0:10]
data7 = frenchp[frenchp.Category == 'Sanctions']
data7 = data7[0:10]
data8 = frenchp[frenchp.Category == 'War']
data8 = data8[0:10]
frames2 = [data1,data2,data3,data4,data5,data6,data7,data8]
frenchmostra = pd.concat(frames2)

frenchmostra.to_csv("subset_french.csv")
frenchmostra

symbol     jobno       dat language  \
0                        A/47/2  N9332437  19930602   French   
1                      A/47/883  N9307475  19930205   French   
2                      A/47/886  N9308030  19930209   French   
3                      A/47/965  N9335138  19930615   French   
4                      A/47/967  N9336113  19930615   French   
5                      A/47/977  N9340548  19930719   French   
6                      A/47/981  N9341116  19930722   French   
7                 A/47/12/ADD.1  N9318380  19930101   French   
8                  A/47/3/REV.1  N9315784  19930318   French   
9                       A/48/12  N9353417  19931006   French   
999              A/47/693/ADD.1  N9315721  19930318   French   
1000                   A/48/381  N9348962  19930908   French   
1001                   A/48/616  N9365833  19931124   French   
1002                   A/48/670  N9368784  19931206   French   
1003                   A/48/671  N9368778  19931206   French   
1004                   A/48/672  N9368906  19931207   French   
1005                   A/48/673  N9369598  19931209   French   
1006                   A/48/687  N9369067  19931207   French   
1007                   A/48/688  N9369583  19931209   French   
1008                  A/48/L.40  N9368302  19931206   French   
1998                  A/47/1020  N9350449  19930916   French   
1999                  A/47/1021  N9350872  19930917   French   
2000                  A/47/1024  N9351038  19930920   French   
2001  A/47/6/REV.1[VOL.I](SUPP)  N9310614  19930101   French   
2002                   A/48/126  N9319328  19930402   French   
2003                   A/48/128  N9319827  19930406   French   
2004                   A/48/131  N9320494  19930407   French   
2005                   A/48/133  N9321284  19930412   French   
2006                   A/48/135  N9321230  19930412   French   
2007                   A/48/137  N9321589  19930413   French   
...                         ...       ...       ...      ...   
4995                  A/47/1004  N9346992  19930826   French   
4996                  A/47/1015  N9349298  19930910   French   
4997                   A/47/906  N9314275  19930311   French   
4998                   A/47/916  N9318645  19930331   French   
4999                   A/47/925  N9321750  19930414   French   
5000                   A/47/927  N9321974  19930415   French   
5001                   A/47/932  N9324388  19930428   French   
5002                   A/47/944  N9326626  19930507   French   
5003                   A/47/969  N9336852  19930628   French   
5004                   A/47/978  N9340758  19930720   French   
5994                   A/47/947  N9327737  19930512   French   
5995                   A/47/952  N9331452  19930528   French   
5996                   A/47/958  N9331529  19930528   French   
5997                   A/47/962  N9333600  19930608   French   
5998                   A/47/974  N9338790  19930706   French   
5999                   A/47/975  N9338982  19930712   French   
6000                   A/48/127  N9320432  19930405   French   
6001                   A/48/155  N9322540  19930419   French   
6002                   A/48/212  N9335411  19930616   French   
6003                    A/48/22  N9361520  19931117   French   
6993                   A/47/897  N9319254  19930402   French   
6994                   A/47/909  N9316577  19930322   French   
6995                   A/47/911  N9316904  19930322   French   
6996                   A/47/919  N9319022  19930401   French   
6997                   A/47/924  N9321197  19930412   French   
6998                   A/47/928  N9322511  19930419   French   
6999                   A/47/935  N9324581  19930429   French   
7000                   A/47/938  N9325199  19930504   French   
7001                   A/47/939  N9325511  19930504   French   
7002                   A/47/943  N9326609  19930507   French   

                                               keywords 

In [14]:
import pandas as pd
frenchp = pd.read_csv("frenchp.csv",)

In [44]:
subset = pd.read_csv("subset_jobno.csv",header=None)
subset.rename(columns={0:'id',
                          1:'symbol',
                          }, 
                 inplace=True)
subset_french = pd.merge(subset,french, on="symbol",how='inner')
subset_french.to_csv("subset_french2.csv")

In [3]:
frenchp.groupby('Category')[['jobno']].count()

jobno
Category            
Assistance       999
Consultations    999
Disarment        999
Negotiation      999
Nuclear          999
Peace            999
Sanctions        999
War              999

In [5]:
frenchp.groupby('Category')[['jobno']].count()
s = pd.Series(range(len(frenchp)))
frenchp.set_index(s,inplace=True,append = True)

In [3]:
import pandas as pd
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

In [4]:
X = frenchp.text
y = frenchp.Category
y

0       Assistance
1       Assistance
2       Assistance
3       Assistance
4       Assistance
5       Assistance
6       Assistance
7       Assistance
8       Assistance
9       Assistance
10      Assistance
11      Assistance
12      Assistance
13      Assistance
14      Assistance
15      Assistance
16      Assistance
17      Assistance
18      Assistance
19      Assistance
20      Assistance
21      Assistance
22      Assistance
23      Assistance
24      Assistance
25      Assistance
26      Assistance
27      Assistance
28      Assistance
29      Assistance
           ...    
7962           War
7963           War
7964           War
7965           War
7966           War
7967           War
7968           War
7969           War
7970           War
7971           War
7972           War
7973           War
7974           War
7975           War
7976           War
7977           War
7978           War
7979           War
7980           War
7981           War
7982           War
7983        

In [8]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 10000000)
pd.set_option('display.width', 1000)

In [9]:
documents = []


#stoplist = set('for a of the and to in to be which some is at that we i who whom show via may my our might as well'.split())
stemmer = SnowballStemmer(language='french')

for i in range(len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[i]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.stem(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)
    pickle.dump( documents, open( 'texts_french_stem.p', "wb" ) )

In [1]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
import json 

In [2]:
documents = pickle.load(open('texts_french_stem.p', 'rb'))

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('french'))
X = vectorizer.fit_transform(documents).toarray()
gtfre = vectorizer.get_feature_names()
with open ("get_fre.json","w",encoding="utf8")as f: json.dump(gtfre, f)

In [9]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [10]:
from sklearn.model_selection import train_test_split
X = pd.DataFrame(X)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=21)

In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=100, n_estimators=600, max_features=320) 
classifier.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=100, max_features=320, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=600, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [12]:
y_pred = classifier.predict(X_test)


In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[200   4   5  11   1   9   7  10]
 [  2 237   2  10  10   6   1   3]
 [  7  10 169  31  22   9   0  15]
 [ 17   6   9 186   0  10   9  15]
 [  1   3  29   1 201   3   3   0]
 [ 20   4   1  18   0 177   6  14]
 [ 21   3   3   8   2   1 203   6]
 [ 19   1   5  18   3  13   9 169]]
               precision    recall  f1-score   support

   Assistance       0.70      0.81      0.75       247
Consultations       0.88      0.87      0.88       271
    Disarment       0.76      0.64      0.70       263
  Negotiation       0.66      0.74      0.70       252
      Nuclear       0.84      0.83      0.84       241
        Peace       0.78      0.74      0.76       240
    Sanctions       0.85      0.82      0.84       247
          War       0.73      0.71      0.72       237

    micro avg       0.77      0.77      0.77      1998
    macro avg       0.77      0.77      0.77      1998
 weighted avg       0.78      0.77      0.77      1998

0.7717717717717718


In [14]:
with open('classifier', 'wb') as picklefile:
    pickle.dump(classifier,picklefile)

In [17]:
#russian_metrics = confusion_matrix(y_test,y_pred)
french_metrics = classification_report(y_test,y_pred,output_dict=True)
#russian_metrics = accuracy_score(y_test, y_pred)
fra = pd.DataFrame(french_metrics).transpose()
fra.to_csv("fra_metrics.csv")
fra

f1-score  precision    recall  support
Assistance     0.749064   0.696864  0.809717    247.0
Consultations  0.879406   0.884328  0.874539    271.0
Disarment      0.695473   0.757848  0.642586    263.0
Negotiation    0.695327   0.657244  0.738095    252.0
Nuclear        0.837500   0.841004  0.834025    241.0
Peace          0.756410   0.776316  0.737500    240.0
Sanctions      0.837113   0.852941  0.821862    247.0
War            0.720682   0.728448  0.713080    237.0
micro avg      0.771772   0.771772  0.771772   1998.0
macro avg      0.771372   0.774374  0.771425   1998.0
weighted avg   0.771979   0.775292  0.771772   1998.0

In [18]:
frenchp['prev_id'] = frenchp.index
y_test_db = pd.DataFrame(y_test)
y_test_db['id'] = range(len(y_test_db.index))
y_test_db['prev_id'] = y_test_db.index
y_pred_db = pd.DataFrame(y_pred)
y_pred_db['id'] = range(len(y_pred_db.index))
testvspred = pd.merge(y_test_db, y_pred_db, on='id', how='inner')
testfrench = pd.merge(frenchp, testvspred , on='prev_id', how='inner')
testfrench .to_csv("test_french.csv")
testfrench

symbol     jobno       dat language  \
0                 A/47/2  N9332437  19930602   French   
1               A/47/965  N9335138  19930615   French   
2          A/47/12/ADD.1  N9318380  19930101   French   
3               A/48/391  N9351548  19930923   French   
4               A/48/434  N9351831  19931006   French   
5               A/48/453  N9352651  19931006   French   
6               A/48/504  N9356489  19931029   French   
7               A/48/646  N9369423  19931209   French   
8               A/48/698  N9366783  19931129   French   
9               A/48/702  N9367268  19931130   French   
10              A/48/709  N9367951  19931202   French   
11              A/48/711  N9367957  19931202   French   
12              A/48/716  N9371106  19931215   French   
13              A/48/799  N9371959  19931220   French   
14              A/48/835  N9373043  19931229   French   
15            A/48/PV.15  N9386735  19931022   French   
16             A/48/PV.5  N9386612  19931006   French   
17             A/48/PV.7  N9386624  19931008   French   
18        A/48/323/ADD.1  N9362951  19931112   French   
19        A/48/625/ADD.1  N9369715  19931215   French   
20        A/48/632/ADD.3  N9370987  19931216   French   
21           A/AC.96/815  G9302392  19930831   French   
22        A/AC.96/SR.481  G9302672  19931008   French   
23           A/C.3/48/14  N9363748  19931116   French   
24           A/C.5/48/41  N9369348  19931208   French   
25    A/C.5/48/48/ADD.40  N9373077  19931213   French   
26           A/RES/48/23  NR071340  19931203   French   
27           A/RES/48/88  NR071405  19931229   French   
28             E/1993/90  N9335731  19930621   French   
29        E/CN.4/1994/49  G9410628  19931223   French   
...                  ...       ...       ...      ...   
1968      S/PRST/1995/35  N9522600  19950728   French   
1969      S/PRST/1995/51  N9530777  19951012   French   
1970           A/50/1037  N9623757  19960911   French   
1971            A/50/877  N9603670  19960215   French   
1972            A/50/937  N9609843  19960418   French   
1973            A/50/940  N9610029  19960419   French   
1974            A/50/941  N9610124  19960422   French   
1975            A/50/961  N9613355  19960528   French   
1976            A/50/992  N9616842  19960705   French   
1977            A/51/185  N9616400  19960701   French   
1978            A/51/392  N9625264  19960923   French   
1979            A/51/411  N9625410  19960926   French   
1980            A/51/453  N9626315  19961004   French   
1981            A/51/562  N9629208  19961025   French   
1982     A/51/566/ADD.11  N9634562  19961129   French   
1983          A/C.1/51/7  N9627113  19961010   French   
1984    CCW/CONF.I/SR.11  G9661112  19960429   French   
1985             CD/1381  G9660309  19960126   French   
1986      CERD/C/SR.1064  G9418646  19961025   French   
1987     E/CN.4/1996/163  G9612476  19960418   French   
1988   E/CN.4/1996/SR.43  G9612590  19960523   French   
1989   E/CN.4/1996/SR.49  G9612608  19960606   French   
1990          S/1996/255  N9608653  19960409   French   
1991          S/1996/299  N9609837  19960418   French   
1992          S/1996/330  N9611278  19960502   French   
1993          S/1996/386  N9613384  19960529   French   
1994          S/1996/410  N9614323  19960607   French   
1995          S/1996/413  N9614383  19960610   French   
1996          S/1996/438  N9615092  19960617   French   
1997          S/1996/561  N9617784  19960717   French   

                                               keywords  \
0     ['DISPUTES', 'LIBYA', 'UNITED STATES', 'BELIZE...   
1     ['PREVENTIVE DIPLOMACY', 'FACT-FINDING MISSION...   
2     ['HUMANITARIAN ASSISTANCE', 'TREATIES', 'REFUG...   
3     ['REFUGEE ASSISTANCE', 'HUMANITARIAN ASSISTANC...   
4     ['EMERGENCY RELIEF', 'FOOD AID', 'HUMANITARIAN...   
5     ['DISPLACED PERSONS', 'RECONSTRUCTION', 'ECONO...   
6     ['HUMANITARIAN ASSISTANCE', 'EMERGENCY RELIEF'...   
7     ['UNI