In [31]:
import pandas as pd
russian = pd.read_csv("russian.csv")
russian

symbol     jobno       dat language  \
0                 A/47/1000  N9344927  19930813  Russian   
1                 A/47/1001  N9345600  19930820  Russian   
2                 A/47/1004  N9346993  19930826  Russian   
3                 A/47/1008  N9348299  19930902  Russian   
4                 A/47/1010  N9348539  19930903  Russian   
5                 A/47/1015  N9349299  19930910  Russian   
6                 A/47/1019  N9350237  19930915  Russian   
7                 A/47/1020  N9350450  19930916  Russian   
8                 A/47/1021  N9350873  19930917  Russian   
9                 A/47/1023  N9351564  19930923  Russian   
10                A/47/1024  N9351039  19930920  Russian   
11                 A/47/977  N9340549  19930719  Russian   
12                 A/47/986  N9343102  19930730  Russian   
13                 A/47/988  N9341946  19930726  Russian   
14                 A/47/990  N9342911  19930730  Russian   
15                 A/47/992  N9342572  19930728  Russian   
16                 A/47/993  N9342847  19930729  Russian   
17                 A/47/994  N9342858  19930802  Russian   
18                 A/47/995  N9343090  19930730  Russian   
19                 A/47/996  N9343278  19930802  Russian   
20                 A/47/998  N9344506  19930813  Russian   
21               A/47/PV.93  N9262286  19930122  Russian   
22           A/47/733/ADD.1  N9340359  19930727  Russian   
23           A/47/734/ADD.2  N9349112  19930909  Russian   
24           A/47/751/ADD.1  N9338697  19930708  Russian   
25           A/47/796/ADD.2  N9349118  19930909  Russian   
26           A/47/797/ADD.2  N9349146  19930909  Russian   
27           A/47/823/ADD.1  N9349105  19930909  Russian   
28           A/47/824/ADD.1  N9349089  19930909  Russian   
29           A/47/825/ADD.1  N9349140  19930909  Russian   
...                     ...       ...       ...      ...   
27266       S/AC.55/2014/14  N1430129  20140415  Russian   
27267       S/AC.55/2014/15  N1430938  20140422  Russian   
27268       S/AC.55/2014/16  N1431387  20140425  Russian   
27269        S/AC.55/2014/2  N1427198  20140321  Russian   
27270        S/AC.55/2014/3  N1427278  20140320  Russian   
27271        S/AC.55/2014/4  N1427317  20140320  Russian   
27272        S/AC.55/2014/5  N1427485  20140305  Russian   
27273        S/AC.55/2014/6  N1427520  20140305  Russian   
27274        S/AC.55/2014/7  N1427686  20140324  Russian   
27275        S/AC.55/2014/8  N1427860  20140326  Russian   
27276        S/AC.55/2014/9  N1429194  20140407  Russian   
27277  S/AC.55/2014/1/ADD.1  N1429386  20140404  Russian   
27278  S/AC.55/2014/5/ADD.1  N1430944  20140423  Russian   
27279         S/PRST/2014/1  N1420493  20140110  Russian   
27280         S/PRST/2014/3  N1423340  20140212  Russian   
27281         S/PRST/2014/4  N1423621  20140214  Russian   
27282         S/PRST/2014/5  N1424279  20140221  Russian   
27283         S/PRST/2014/7  N1432406  20140507  Russian   
27284     S/RES/2134 (2014)  N1421896  20140128  Russian   
27285     S/RES/2135 (2014)  N1422176  20140130  Russian   
27286     S/RES/2139 (2014)  N1424341  20140222  Russian   
27287     S/RES/2140 (2014)  N1424709  20140226  Russian   
27288     S/RES/2141 (2014)  N1425365  20140305  Russian   
27289     S/RES/2145 (2014)  N1426685  20140316  Russian   
27290     S/RES/2148 (2014)  N1428956  20140403  Russian   
27291     S/RES/2149 (2014)  N1429583  20140410  Russian   
27292     S/RES/2151 (2014)  N1431393  20140428  Russian   
27293     S/RES/2152 (2014)  N1431483  20140429  Russian   
27294     S/RES/2153 (2014)  N1431495  20140429  Russian   
27295     S/RES/2154 (2014)  N1432860  20140508  Russian   

                                                keywords     Category  \
0      ['NEGOTIATION', 'POLITICAL CONDITIONS', 'HAITI...  Negotiation   
1      ['MAPS', 'PEACEKEEPING OPERATIONS', 'CYPRUS', ...        Peace   
2      ['PEACEKEEPING OPERATIONS', 'CYPRUS', 'FINANCI...        Peace   
3      [

In [6]:
import pandas as pd
russianp = pd.read_csv("russianp.csv")


In [4]:
russianp.head(10)

symbol     jobno       dat language  \
0  A/47/PV.93  N9262286  19930122  Russian   
1     A/48/12  N9353418  19931006  Russian   
2      A/48/2  N9355949  19931019  Russian   
3      A/48/3  N9350225  19930915  Russian   
4    A/48/323  N9345612  19930924  Russian   
5    A/48/349  N9347206  19930827  Russian   
6    A/48/391  N9351549  19930923  Russian   
7    A/48/392  N9349322  19930922  Russian   
8    A/48/434  N9351832  19931006  Russian   
9    A/48/453  N9352652  19931006  Russian   

                                            keywords    Category  \
0  ['DEVELOPMENT ASSISTANCE', 'EMERGENCY RELIEF',...  Assistance   
1  ['REFUGEE ASSISTANCE', 'AFRICA', 'NORTH AMERIC...  Assistance   
2  ['BOUNDARIES', 'SPECIAL MISSIONS', 'IRAQ', 'KU...  Assistance   
3  ['NUCLEAR ACCIDENTS', 'CHERNOBYL (UKRAINE)', '...  Assistance   
4  ['RECONSTRUCTION', 'HUMANITARIAN ASSISTANCE', ...  Assistance   
5  ['PEACEKEEPING OPERATIONS', 'MILITARY PERSONNE...  Assistance   
6  ['REFUGEE ASSISTANCE', 'HUMANITARIAN ASSISTANC...  Assistance   
7  ['EDUCATIONAL ASSISTANCE', 'FOOD AID', 'RECONS...  Assistance   
8  ['EMERGENCY RELIEF', 'FOOD AID', 'HUMANITARIAN...  Assistance   
9  ['DISPLACED PERSONS', 'RECONSTRUCTION', 'ECONO...  Assistance   

                                               paths  \
0  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\47\...   
1  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
2  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
3  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
4  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
5  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
6  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
7  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
8  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   
9  D:/un_dataset/RUSSIAN/UNv1.0-TEI/ru/1993\a\48\...   

                                                text  prev_id  
0  PROVISIONAL. A/47/PV.93. 21 July 1993. RUSSIAN...        0  
1  Distr. GENERAL. A/48/12. 6 October 1993. RUSSI...        1  
2  Distr. GENERAL. A/48/2. 19 October 1993. RUSSI...        2  
3  Distr. GENERAL. A/48/3. 15 September 1993. RUS...        3  
4  A/48/323. Russian. Page. Distr. GENERAL. А/48/...        4  
5  A/48/349. S/26358. Russian. Page. Distr. GENER...        5  
6  A/48/391. Russian. Page. Distr. GENERAL. 23 Se...        6  
7  A/48/392. Russian. Page. Distr. GENERAL. 22 Se...        7  
8  A/48/434. Russian. Page. Distr. GENERAL. 6 Oct...        8  
9  A/48/453. Russian. Page. Distr. GENERAL. 6 Oct...        9

In [33]:
subset = pd.read_csv("subset_jobno.csv",header=None)
subset.rename(columns={0:'id',
                          1:'symbol',
                          }, 
                 inplace=True)
subset_russian = pd.merge(subset,russian, on="symbol",how='inner')
subset_russian
subset_russian.to_csv("subset_russian2.csv")

In [3]:
russianp.groupby('Category')[['jobno']].count()

jobno
Category            
Assistance       999
Consultations    999
Disarment        999
Negotiation      999
Nuclear          999
Peace            999
Sanctions        999
War              999

In [7]:

s = pd.Series(range(len(russianp)))
russianp.set_index(s,inplace=True,append = True)

In [8]:

import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

In [9]:
X = russianp.text
y = russianp.Category


In [19]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 500)
pd.set_option('display.width', 500)

In [9]:
documents = []
jobno = []
titols.append(os.path.basename(n).replace('.txt', ''))


stemmer = SnowballStemmer(language='russian')

for i in range(len(X)):
  
    document = re.sub(r'\W', ' ', str(X[i]))
    

    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    

    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    

    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    

    document = document.lower()
    

    document = document.split()

    document = [stemmer.stem(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)
    pickle.dump( documents, open( 'texts_russian_stem.p', "wb" ) )

In [3]:
import pandas as pd
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
import json 

In [10]:
documents = pickle.load(open('texts_russian_stem.p', 'rb'))

In [121]:
documents2 = list(enumerate(documents))

In [125]:

russ_dict = {doc[0]:doc[1] for doc in documents2}
 

In [113]:
russ_dict = dict((documents[0],documents[-1]) for i in documents)

In [126]:
print(russ_dict[1])

1 distr genera 48 12 6 october 1993 russia origina english and french сорок восьм сесс пункт 113 повестк дня доклад верховн комиссар организац объединен нац по дел беженц резюм настоя доклад подготовл в соответств со стат 11 устав управлен верховн комиссар организац объединен нац по дел беженц утвержден генеральн ассамбле в резолюц 428 от 14 декабр 1950 год в котор в частност предусмотр что верховн комиссар ежегодн представля доклад генеральн ассамбл через экономическ и социальн совет в нем охарактеризова основн вид деятельн провод управлен в интерес беженц и перемещен лиц в соответств с положен устав и послед резолюц генеральн ассамбл к ним относ международн защит чрезвычайн помощ и достижен долгосрочн решен на основ добровольн репатриац расселен на мест в стран убежищ ил переселен в друг стран в доклад такж содерж информац о сотрудничеств с друг член систем организац объединен нац и с межправительствен и неправительствен организац а такж информац по финансов вопрос и деятельн в облас

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=3500, min_df=5, max_df=0.7, stop_words=stopwords.words('russian'))
X = vectorizer.fit_transform(documents).toarray()
gtrus = vectorizer.get_feature_names()
with open ("get_rus.json","w",encoding="utf8")as f: json.dump(gtrus, f)

In [76]:
len(X)

7992

In [24]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [25]:
from sklearn.model_selection import train_test_split
X = pd.DataFrame(X)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=21)

In [27]:
from sklearn.ensemble import RandomForestClassifier
rusclassifier = RandomForestClassifier(max_depth=100, n_estimators=600, max_features=320) 
rusclassifier.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=100, max_features=320, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=600, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [28]:
y_pred = rusclassifier.predict(X_test)

In [16]:
russianp['prev_id'] = russianp.index
y_test_db = pd.DataFrame(y_test)
y_test_db['id'] = range(len(y_test_db.index))
y_test_db['prev_id'] = y_test_db.index
y_pred_db = pd.DataFrame(y_pred)
y_pred_db['id'] = range(len(y_pred_db.index))
testvspred = pd.merge(y_test_db, y_pred_db, on='id', how='inner')

In [17]:
testrussian = pd.merge(russianp, testvspred , on='prev_id', how='inner')

In [40]:
testrussian
#testrussian.to_csv("test_russian.csv",index=False)

symbol     jobno       dat language  \
0                A/47/PV.93  N9262286  19930122  Russian   
1                    A/48/2  N9355949  19931019  Russian   
2                    A/48/3  N9350225  19930915  Russian   
3                  A/48/323  N9345612  19930924  Russian   
4                  A/48/392  N9349322  19930922  Russian   
5                  A/48/523  N9358081  19931025  Russian   
6                  A/48/536  N9358075  19931104  Russian   
7                  A/48/602  N9363537  19931115  Russian   
8                  A/48/626  N9365810  19931124  Russian   
9                  A/48/648  N9369355  19931208  Russian   
10                 A/48/660  N9366353  19931126  Russian   
11                 A/48/698  N9366784  19931129  Russian   
12                 A/48/711  N9367958  19931202  Russian   
13                 A/48/739  N9369105  19931207  Russian   
14                 A/48/740  N9370362  19931213  Russian   
15                 A/48/782  N9371636  19931217  Russian   
16                 A/48/785  N9371618  19931217  Russian   
17                 A/48/799  N9371960  19931220  Russian   
18               A/48/PV.20  N9386790  19931026  Russian   
19               A/48/PV.27  N9386857  19931103  Russian   
20               A/48/PV.43  N9387014  19931122  Russian   
21                A/48/PV.8  N9386631  19931011  Russian   
22               A/48/PV.83  N9387427  19930120  Russian   
23           A/C.2/48/SR.24  N9382162  19931221  Russian   
24              A/C.3/48/17  N9368653  19931123  Russian   
25            A/C.3/48/L.74  N9367233  19931130  Russian   
26           A/C.3/48/SR.23  N9382135  19931214  Russian   
27           A/C.3/48/SR.24  N9382168  19931201  Russian   
28           A/C.3/48/SR.25  N9382204  19931213  Russian   
29              A/C.5/48/41  N9369349  19931208  Russian   
30       A/C.5/48/48/ADD.40  N9373078  19931213  Russian   
31              A/RES/48/88  NR071638  19931229  Russian   
32                  S/26182  N9346587  19930824  Russian   
33                  S/26200  N9343290  19930804  Russian   
34                  S/26204  N9343145  19930802  Russian   
35                  S/26233  N9343427  19930803  Russian   
36                  S/26310  N9345356  19930816  Russian   
37                  S/26341  N9346320  19930823  Russian   
38                  S/26385  N9347790  19930830  Russian   
39                  S/26395  N9348259  19930901  Russian   
40                  S/26419  N9348999  19930908  Russian   
41                  S/26422  N9348545  19930909  Russian   
42                  S/26426  N9349649  19930913  Russian   
43                  S/26434  N9349605  19930913  Russian   
44                  S/26479  N9351215  19930921  Russian   
45                  S/26481  N9351221  19930921  Russian   
46                  S/26519  N9354053  19931005  Russian   
47                  S/26582  N9355737  19931014  Russian   
48                  S/26592  N9356640  19931019  Russian   
49                  S/26601  N9356604  19931019  Russian   
50                  S/26644  N9358645  19931027  Russian   
51                  S/26716  N9362490  19931109  Russian   
52                  S/26719  N9363062  19931111  Russian   
53                  S/26743  N9363381  19931114  Russian   
54                  S/26764  N9364549  19931118  Russian   
55                  S/26783  N9365120  19931122  Russian   
56                  S/26868  N9369938  19931213  Russian   
57                  S/26872  N9370195  19931203  Russian   
58                  S/26877  N9371020  19931214  Russian   
59                  S/26892  N9371756  19931218  Russian   
60           S/25070/ADD.45  N9365651  19931122  Russian   
61          S/RES/856(1993)  NR070227  19930810  Russian   
62          S/RES/864(1993)  NR070235  19930915  Russian   
63          S/RES/872(1993)  NR070243  19931005  Russian   
64          S/RES/890(1993)  NR070261  19931215  Russian   
65            A/48/12(SUPP)  N9404467  19940127  Russian   
6

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[234   4   8   9   2  18  10  12]
 [  5 272  18   6   4  11   4   2]
 [ 14  14 175  26  57  13   3  15]
 [ 17   8  10 228   2   7   4  24]
 [  1   6  32   1 252   0   4   0]
 [ 24   6   2  13   0 222   4  24]
 [ 12   6   5  12   0   8 229  15]
 [ 19   4  21  16   2   4   3 215]]
               precision    recall  f1-score   support

   Assistance       0.72      0.79      0.75       297
Consultations       0.85      0.84      0.85       322
    Disarment       0.65      0.55      0.60       317
  Negotiation       0.73      0.76      0.75       300
      Nuclear       0.79      0.85      0.82       296
        Peace       0.78      0.75      0.77       295
    Sanctions       0.88      0.80      0.84       287
          War       0.70      0.76      0.73       284

    micro avg       0.76      0.76      0.76      2398
    macro avg       0.76      0.76      0.76      2398
 weighted avg       0.76      0.76      0.76      2398

0.7618849040867389


In [39]:
#russian_metrics = confusion_matrix(y_test,y_pred)
russian_metrics = classification_report(y_test,y_pred,output_dict=True)
#russian_metrics = accuracy_score(y_test, y_pred)
rus = pd.DataFrame(russian_metrics).transpose()
rus.to_csv("rus_metrics.csv")

In [30]:
with open('rusclassifier2', 'wb') as picklefile:
    pickle.dump(rusclassifier,picklefile)

In [27]:
with open('rusclassifier', 'rb') as training_model:
    model = pickle.load(training_model)

In [37]:
y_pred2 = model.predict(X_test)

print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2)) 

[[82  2  1  2  1  7  5  3]
 [ 1 92  9  1  2  2  3  0]
 [ 5  8 57  5 16  4  0  4]
 [ 5  5  7 76  0  4  2 10]
 [ 0  0 12  0 91  0  3  0]
 [ 9  1  0  2  0 62  2  6]
 [ 5  3  1  2  0  2 81  6]
 [ 7  3  9  3  0  3  1 65]]
               precision    recall  f1-score   support

   Assistance       0.72      0.80      0.76       103
Consultations       0.81      0.84      0.82       110
    Disarment       0.59      0.58      0.58        99
  Negotiation       0.84      0.70      0.76       109
      Nuclear       0.83      0.86      0.84       106
        Peace       0.74      0.76      0.75        82
    Sanctions       0.84      0.81      0.82       100
          War       0.69      0.71      0.70        91

    micro avg       0.76      0.76      0.76       800
    macro avg       0.76      0.76      0.75       800
 weighted avg       0.76      0.76      0.76       800

0.7575
