In [39]:
import pandas as pd
english = pd.read_csv("english.csv")
english.index

RangeIndex(start=0, stop=30223, step=1)

In [2]:
englishp.columns

Index(['symbol', 'jobno', 'dat', 'language', 'keywords', 'Category', 'paths',
       'text'],
      dtype='object')

In [3]:
data1 = englishp[englishp.Category == 'Assistance']
data1 = data1[1:1000]
data2 = englishp[englishp.Category == 'consultations']
data2 = data2[1:1000]
data3 = englishp[englishp.Category == 'disarment']
data3 = data3[1:1000]
data4 = englishp[englishp.Category == 'Negotiation']
data4 = data4[1:1000]
data5 = englishp[englishp.Category == 'Nuclear']
data5 = data5[1:1000]
data6 = englishp[englishp.Category == 'Peace']
data6 = data6[1:1000]
data7 = englishp[englishp.Category == 'Sanctions']
data7 = data7[1:1000]
data8 = englishp[englishp.Category == 'war']
data8 = data8[1:1000]

In [20]:
frames = [data1,data2,data3,data4,data5,data6,data7,data8]
englishp = pd.concat(frames)

englishp

symbol     jobno       dat language  \
22      A/47/965  N9335137  19930615  English   
23      A/47/967  N9336112  19930615  English   
27      A/47/977  N9340547  19930719  English   
30      A/47/981  N9341115  19930722  English   
54       A/48/12  N9353416  19931006  English   
76      A/48/215  N9336355  19930621  English   
92        A/48/3  N9350223  19930915  English   
102     A/48/323  N9345610  19930924  English   
113     A/48/349  N9347204  19930827  English   
130     A/48/391  N9351547  19930923  English   
131     A/48/392  N9349320  19930922  English   
145     A/48/434  N9351830  19931006  English   
153     A/48/453  N9352650  19931006  English   
162     A/48/467  N9353785  19931022  English   
164     A/48/473  N9354033  19931008  English   
168     A/48/484  N9354826  19931018  English   
177     A/48/504  N9356488  19931029  English   
182     A/48/523  N9358079  19931025  English   
184     A/48/534  N9357736  19931022  English   
186     A/48/536  N9358073  19931104  English   
200     A/48/595  N9363078  19931112  English   
201     A/48/602  N9363535  19931115  English   
208     A/48/626  N9365808  19931124  English   
209     A/48/636  N9365168  19931124  English   
210     A/48/637  N9365630  19931123  English   
215     A/48/646  N9369422  19931209  English   
216     A/48/648  N9369353  19931208  English   
218     A/48/654  N9367804  19931202  English   
220     A/48/660  N9366351  19931126  English   
241     A/48/685  N9369901  19931210  English   
...          ...       ...       ...      ...   
6473  S/1996/710  N9622621  19960830  English   
6474  S/1996/711  N9622729  19960903  English   
6475  S/1996/712  N9622723  19960903  English   
6477  S/1996/715  N9622841  19960904  English   
6478  S/1996/716  N9622847  19960904  English   
6483  S/1996/728  N9623342  19960909  English   
6484  S/1996/729  N9623336  19960909  English   
6486  S/1996/733  N9623538  19960910  English   
6487  S/1996/735  N9623576  19960910  English   
6492  S/1996/757  N9624289  19960916  English   
6494  S/1996/771  N9625052  19960923  English   
6495  S/1996/773  N9625040  19960923  English   
6496  S/1996/774  N9625064  19960923  English   
6499  S/1996/781  N9625351  19960925  English   
6501  S/1996/784  N9625309  19960925  English   
6503  S/1996/790  N9625479  19960926  English   
6504  S/1996/792  N9625485  19960926  English   
6505  S/1996/800  N9625659  19960927  English   
6510  S/1996/806  N9625788  19960930  English   
6511  S/1996/808  N9625818  19960930  English   
6512  S/1996/810  N9625794  19960930  English   
6513  S/1996/811  N9625800  19960930  English   
6518   S/1996/82  N9602450  19960202  English   
6522  S/1996/823  N9626154  19961002  English   
6524  S/1996/829  N9626503  19961007  English   
6530  S/1996/845  N9627139  19961011  English   
6531  S/1996/847  N9627247  19961011  English   
6536  S/1996/861  N9628165  19961018  English   
6537  S/1996/862  N9628171  19961018  English   
6544  S/1996/877  N9629039  19961025  English   

                                               keywords    Category  \
22    ['PREVENTIVE DIPLOMACY', 'FACT-FINDING MISSION...  Assistance   
23    ['PEACEKEEPING OPERATIONS', 'CROATIA', 'HUMANI...  Assistance   
27    ['POLITICAL STATUS', 'JAMMU AND KASHMIR', 'CEA...  Assistance   
30    ['HUMANITARIAN ASSISTANCE', 'PEACEKEEPING OPER...  Assistance   
54    ['REFUGEE ASSISTANCE', 'AFRICA', 'NORTH AMERIC...  Assistance   
76    ['DEVELOPMENT ASSISTANCE', 'RECONSTRUCTION', '...  Assistance   
92    ['NUCLEAR ACCIDENTS', 'CHERNOBYL (UKRAINE)', '...  Assistance   
102   ['RECONSTRUCTION', 'HUMANITARIAN ASSISTANCE', ...  Assistance   
113   ['PEACEKEEPING OPERATIONS', 'MILITARY PERSONNE...  Assistance   
130   ['REFUGEE ASSISTANCE', 'HUMANITARIAN ASSISTANC...  Assistance   
131   ['EDUCATIONAL ASSISTANCE', 'FOOD AID', 'RECONS...  Assistance   
145   ['EMERGENCY RELIEF', 'FOOD AID', 'HUMANITARIAN...  Assistance   
153   ['DISPLACED PERSONS', 'RECONSTRUCTION', 'E

In [16]:
data1 = englishp[englishp.Category == 'Assistance']
data1 = data1[0:10]
data2 = englishp[englishp.Category == 'consultations']
data2 = data2[0:10]
data3 = englishp[englishp.Category == 'disarment']
data3 = data3[0:10]
data4 = englishp[englishp.Category == 'Negotiation']
data4 = data4[0:10]
data5 = englishp[englishp.Category == 'Nuclear']
data5 = data5[0:10]
data6 = englishp[englishp.Category == 'Peace']
data6 = data6[0:10]
data7 = englishp[englishp.Category == 'Sanctions']
data7 = data7[0:10]
data8 = englishp[englishp.Category == 'war']
data8 = data8[0:10]
frames2 = [data1,data2,data3,data4,data5,data6,data7,data8]
englishmostra = pd.concat(frames2)

englishmostra.to_csv("subset_english.csv")
len(englishmostra)

80

In [13]:
englishp = pd.read_csv("englishp.csv")

In [42]:
subset = pd.read_csv("subset_jobno.csv",header=None)
subset.rename(columns={0:'id',
                          1:'symbol',
                          }, 
                 inplace=True)
subset_english = pd.merge(subset,english, on="symbol",how='inner')
subset_english
subset_english.to_csv("subset_english2.csv")

In [14]:
englishp.groupby('Category')[['jobno']].count()
s = pd.Series(range(len(englishp)))
englishp.set_index(s,inplace=True,append = True)

In [61]:
englishp.index

MultiIndex(levels=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 

In [2]:
import pandas as pd
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

In [16]:
X = englishp.text
y = englishp.Category


In [53]:
X
df = pd.DataFrame(data=X)
df.to_csv("df1.csv",index=False)

In [64]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 10000000)
pd.set_option('display.width', 1000)

In [68]:
print(len(X))

7992


In [66]:
for i in X:
    print((len(i)))


35458
5851
1094
3520
157051
7092
305008
97283
26147
16798
43691
61688
78542
60573
44424
3996
57483
15025
11188
110063
829
5772
32866
49076
1566
61396
36982
25001
3804
20119
191249
2659
2376
3232
5395
1091
9898
58309
6427
5322
6017
2009
9106
6755
1624
1782
6914
3560
7309
11976
3235
1683
114688
209578
186239
90359
101666
197610
118602
108612
78475
127690
133006
109550
27886
113745
95185
231369
105564
123874
125582
111095
83075
86133
258068
120430
125352
135125
89947
960
70289
168747
72941
89444
76186
58395
75629
61937
77984
63114
39349
132429
83525
18069
65096
48796
7508
54174
8605
6115
12641
18278
36722
27050
38120
9275
3899
1750
7411
25444
30400
2552
15175
4937
14849
46164
82506
40738
944
71961
7341
404265
10570
132169
46853
39660
16598
17451
37729
12913
5399
237689
54300
55008
2970
9554
837
2131
2667
2500
42252
605
436
12071
27433
2162
2499
5212
2439
2321
959
1688
4280
4128
3359
27115
12535
2297
5319
20956
3355
6340
6210
40422
6221
9015
14696
12124
8364
1387
2100
7416
2403
1317
29085


6038
4806
5421
8319
7469
3148
1987
10497
10233
9133
36729
15490
5215
8147
7817
5099
2520
783
20557
5502
11731
9980
3194
6131
9487
5384
6684
4327
2904
1984
6256
15103
6834
6356
2890
7725
8765
4494
4732
55053
9297
7071
2741
73849
26451
59792
6805
62330
57044
19920
12155
14667
1045
816
946
806
971
947
968
805
1933
858
1150
970
920
10718
4923
14593
5083
55424
4794
35993
16284
7227
3217
3177
4695
15886
909
31636
14762
14414
60781
4779
22890
23088
824
7210
5591
1999
4997
4837
39116
6616
3604
20021
99204
99015
82833
4099
4262
13229
55359
56138
4024
38302
36085
61540
3911
70330
26867
73312
3197
239072
9173
8984
6291
15758
29074
6023
6019
3835
1950
41486
13717
16920
25279
23965
10846
3149
35427
8202
14208
40989
10329
16817
11564
112966
1672
17758
11889
25400
67252
29793
52093
45123
3895
1429
3042
6020
4489
3962
9797
4387
4842
4090
13592
7581
9115
4900
3673
5496
2064
13512
4402
4689
48011
7951
5832
47369
12182
6471
6869
21674
8651
19693
2948
2502
878
2470
2042
2493
3826
2095
2652
40812
6422
4450

8815
4687
4776
7264
6093
2660
24179
2581
2112
3519
3557
22161
2500
4569
3196
3145
3515
2770
2647
1908
6715
3000
2553
2357
1667
2578
43378
2310
76036
2527
193629
89003
122553
112652
79689
3368
1414
27184
51441
3975
4844
67687
19419
26346
13160
3567
935
1783
2381
1898
2070
4831
1709
1526
2037
1838
2288
2274
7128
2338
2959
2768
1555
2440
3765
2226
1688
3136
2001
2336
1980
1292
2398
2295
3542
8894
56084
3560
1966
25871
35580
32189
3020
42071
3917
2993
2508
3444
7934
45952
2942
2739
113845
2307
1981
5714
6760
4478
72088
134895
4350
18294
134333
83833
114115
130969
3360
7083
44889
3514
2230
1579
6576
2078
83578
33811
2737
14430
25086
24180
62601
4335
14404
4954
119320
205110
9023
43522
4560
954
40175
13998
834
104916
832
5461
3250
18686
20255
10528
2166
2131
2401
1948
2652
3503
1651
5173
1716
3013
2344
2590
3600
3685
2800
1210
5231
1994
12205
2236
9537
4328
44683
17195
23308
39809
5017
20316
164121
125511
119743
183205
118670
2436
3379
7653
382
836
773
837
2115
1162
741
799
809
1060
2859
723

8598
6077
4018
6078
14921
14956
8221
7547
17671
2792
12701
18068
4609
12418
7479
4698
12308
12308
8336
4093
4239
9592
5856
10220
7818
8288
7131
7088
5651
20767
6692
3939
14529
39580
7398
3406
8047
6415
8707
15970
8799
6841
5510
8348
7402
7352
7846
6927
5500
4731
5256
7519
6971
953
950
962
13127
3661
2677
8176
6465
11759
4239
5279
23591
8082
12379
7294
2660
1865
280815
40217
4525
19870
145237
5371
84826
13023
7184
3573
53682
5665
38890
23608
4776
6872
4309
3888
2481
2716
115385
133006
129679
132542
122368
124432
140524
130501
136588
116299
90526
105536
54031
1228
959
52721
13962
18014
29043
48877
45927
9250
3399
2002
101919
92372
66443
41220
22704
43804
13680
6771
49642
41990
50231
27476
47514
31609
42972
43337
49669
4174
19703
3562
111802
69423
10456
34078
37314
27781
18846
26208
3043
5087
4145
3245
1525
1309
9876
5680
1451
893
3553
1326
19952
860
8179
1693
4217
89323
8719
3656
765
4926
22679
5231
7053
7484
1387
1146
1065
616
815
1037
752
2931
1026
1188
2860
882
1219
1531
1447
954
1152

In [67]:
documents = []


#stoplist = set('for a of the and to in to be which some is at that we i who whom show via may my our might as well'.split())
stemmer = SnowballStemmer(language='english')

for i in range(len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[i]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.stem(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)
    pickle.dump( documents, open( 'texts_english_stem.p', "wb" ) )

In [11]:
import pandas as pd
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
import json 

In [19]:
documents = pickle.load(open('texts_english_stem.p', 'rb'))

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()
gteng = vectorizer.get_feature_names()
with open ("get_eng.json","w",encoding="utf8")as f: json.dump(gteng, f)

In [72]:
print(len(X))

7992


In [32]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [33]:
from sklearn.model_selection import train_test_split
X = pd.DataFrame(X)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=21)

In [34]:
from sklearn.ensemble import RandomForestClassifier
engclassifier = RandomForestClassifier(max_depth=100, n_estimators=600, max_features=320) 
engclassifier.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=100, max_features=320, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=600, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [35]:

y_pred = engclassifier.predict(X_test)

In [36]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[246  13   3  19   5   3   3   5]
 [ 22 210   5  15  10  12   7  19]
 [  5   3 249   2   1   9  27   0]
 [ 38  19   0 204   5   5   2  22]
 [ 19   4   1   2 244   7   1   9]
 [  5  16   4  11   3 268  13   2]
 [ 17  30  32  10   2   5 201  20]
 [ 22  17   2   8  10   1  15 209]]
               precision    recall  f1-score   support

   Assistance       0.66      0.83      0.73       297
  Negotiation       0.67      0.70      0.69       300
      Nuclear       0.84      0.84      0.84       296
        Peace       0.75      0.69      0.72       295
    Sanctions       0.87      0.85      0.86       287
consultations       0.86      0.83      0.85       322
    disarment       0.75      0.63      0.69       317
          war       0.73      0.74      0.73       284

    micro avg       0.76      0.76      0.76      2398
    macro avg       0.77      0.76      0.76      2398
 weighted avg       0.77      0.76      0.76      2398

0.7635529608006673


In [38]:
with open('engclassifier2', 'wb') as picklefile:
    pickle.dump(engclassifier,picklefile)

In [24]:
#russian_metrics = confusion_matrix(y_test,y_pred)
english_metrics = classification_report(y_test,y_pred,output_dict=True)
#russian_metrics = accuracy_score(y_test, y_pred)
eng = pd.DataFrame(english_metrics).transpose()
eng.to_csv("eng_metrics.csv")
eng
from IPython.display import display, HTML
import 
# Assuming that dataframes df1 and df2 are already defined:
print ("eng:")
display(eng)
print ("Dataframe 2:")
display(HTML(eng.to_html()))
plt.hist(eng)

eng:


f1-score  precision    recall  support
Assistance     0.722302   0.630653  0.845118    297.0
Negotiation    0.707237   0.698052  0.716667    300.0
Nuclear        0.841567   0.848797  0.834459    296.0
Peace          0.712477   0.763566  0.667797    295.0
Sanctions      0.846018   0.859712  0.832753    287.0
consultations  0.849359   0.877483  0.822981    322.0
disarment      0.681208   0.727599  0.640379    317.0
war            0.728873   0.728873  0.728873    284.0
micro avg      0.760634   0.760634  0.760634   2398.0
macro avg      0.761130   0.766842  0.761128   2398.0
weighted avg   0.761144   0.767369  0.760634   2398.0

Dataframe 2:


NameError: name 'plt' is not defined

In [19]:
englishp['prev_id'] = englishp.index
y_test_db = pd.DataFrame(y_test)
y_test_db['id'] = range(len(y_test_db.index))
y_test_db['prev_id'] = y_test_db.index
y_pred_db = pd.DataFrame(y_pred)
y_pred_db['id'] = range(len(y_pred_db.index))
testvspred = pd.merge(y_test_db, y_pred_db, on='id', how='inner')
testenglish = pd.merge(englishp, testvspred , on='prev_id', how='inner')
testenglish .to_csv("test_english.csv")
testenglish

symbol     jobno       dat language  \
0                    A/47/965  N9335137  19930615  English   
1                    A/47/977  N9340547  19930719  English   
2                    A/47/981  N9341115  19930722  English   
3                     A/48/12  N9353416  19931006  English   
4                    A/48/323  N9345610  19930924  English   
5                    A/48/473  N9354033  19931008  English   
6                    A/48/504  N9356488  19931029  English   
7                    A/48/534  N9357736  19931022  English   
8                    A/48/536  N9358073  19931104  English   
9                    A/48/636  N9365168  19931124  English   
10                   A/48/646  N9369422  19931209  English   
11                   A/48/660  N9366351  19931126  English   
12                   A/48/702  N9367267  19931130  English   
13                   A/48/727  N9371117  19931215  English   
14                   A/48/729  N9371151  19931215  English   
15                   A/48/739  N9369103  19931207  English   
16                   A/48/740  N9370360  19931213  English   
17                   A/48/766  N9371123  19931215  English   
18                 A/48/PV.11  N9386680  19931018  English   
19                 A/48/PV.16  N9386746  19931021  English   
20                 A/48/PV.31  N9386897  19931108  English   
21                 A/48/PV.69  N9387315  19931213  English   
22                  A/48/PV.7  N9386623  19931008  English   
23             A/48/323/ADD.1  N9362950  19931112  English   
24             A/48/632/ADD.3  N9370986  19931216  English   
25             A/AC.96/SR.482  G9302701  19931101  English   
26             A/AC.96/SR.483  G9302704  19931011  English   
27             A/AC.96/SR.484  G9302709  19931026  English   
28             A/AC.96/SR.485  G9302712  19931012  English   
29             A/AC.96/SR.487  G9302774  19931012  English   
...                       ...       ...       ...      ...   
2368                 A/51/498  N9627630  19961015  English   
2369                  A/51/58  N9601374  19960123  English   
2370                 A/51/703  N9634744  19961202  English   
2371               A/51/PV.12  N9686290  19960101  English   
2372                A/51/PV.8  N9686264  19960101  English   
2373          A/51/566/ADD.11  N9634561  19961129  English   
2374           A/C.1/51/PV.17  N9686742  19960101  English   
2375              A/RES/50/82  N9676291  19960202  English   
2376     CCW/CONF.I/16(PARTI)  G9661703  19960101  English   
2377  E/CN.4/SUB.2/1996/SR.15  G9613433  19960821  English   
2378              S/1996/1007  N9635127  19961205  English   
2379              S/1996/1036  N9636170  19961212  English   
2380              S/1996/1061  N9637270  19961220  English   
2381               S/1996/281  N9609375  19960414  English   
2382                S/1996/29  N9600639  19960112  English   
2383               S/1996/299  N9609836  19960418  English   
2384               S/1996/330  N9611277  19960502  English   
2385                S/1996/34  N9600944  19960117  English   
2386               S/1996/341  N9611840  19960508  English   
2387               S/1996/359  N9612748  19960521  English   
2388               S/1996/386  N9613383  19960529  English   
2389               S/1996/438  N9615091  19960617  English   
2390               S/1996/675  N9621254  19960820  English   
2391               S/1996/712  N9622723  19960903  English   
2392               S/1996/716  N9622847  19960904  English   
2393               S/1996/773  N9625040  19960923  English   
2394               S/1996/781  N9625351  19960925  English   
2395               S/1996/784  N9625309  19960925  English   
2396               S/1996/792  N9625485  19960926  English   
2397               S/1996/810  N9625794  19960930  English   

                                               keywords  Category_x  \
0     ['PREVENTIVE DIPLOMACY', 'FACT-FINDING MISSION...  Assistance   
1     ['POLITICAL STATUS', 'JAMMU AN

In [118]:
from sklearn.naive_bayes import MultinomialNB

In [122]:
classifiernb = MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
classifiernb.fit(X_train, y_train) 

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [123]:
y_pred = classifiernb.predict(X_test)

In [124]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[176  28   0  27  15  25   6  32]
 [ 24 200   4  12   1  15   6  35]
 [  5   4 247   2   3  21  27   0]
 [ 24  17   0 202   3  21   3  28]
 [ 24  12   3   6 228  15   4  22]
 [  9  16  11  10   0 219  19   1]
 [ 14  34  62  11   1  21 146  14]
 [ 21  20   3   5   5   3  19 207]]
               precision    recall  f1-score   support

   Assistance       0.59      0.57      0.58       309
  Negotiation       0.60      0.67      0.64       297
      Nuclear       0.75      0.80      0.77       309
        Peace       0.73      0.68      0.71       298
    Sanctions       0.89      0.73      0.80       314
consultations       0.64      0.77      0.70       285
    disarment       0.63      0.48      0.55       303
          war       0.61      0.73      0.67       283

    micro avg       0.68      0.68      0.68      2398
    macro avg       0.68      0.68      0.68      2398
 weighted avg       0.68      0.68      0.68      2398

0.6776480400333611


In [125]:
from sklearn.linear_model import LogisticRegression

In [132]:
classifierlog = LogisticRegression(random_state=21)

In [133]:
classifierlog.fit(X_train,y_train)

C:\Users\AlexVaqueroRamirez\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\AlexVaqueroRamirez\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=21, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [134]:
y_pred = classifierlog.predict(X_test)

In [135]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[189  10   3  23   7   8   0   7]
 [ 13 187   7  15   4   4   3  19]
 [  3   2 203   2   2  10  19   0]
 [ 21  16   0 177   5  10   0  11]
 [ 18   2   0   6 205   7   0   9]
 [  6   9   6  11   0 222  11   6]
 [ 17  22  44  16   1   5 145  13]
 [ 15  13   1   9   4   1  12 182]]
               precision    recall  f1-score   support

   Assistance       0.67      0.77      0.71       247
  Negotiation       0.72      0.74      0.73       252
      Nuclear       0.77      0.84      0.80       241
        Peace       0.68      0.74      0.71       240
    Sanctions       0.90      0.83      0.86       247
consultations       0.83      0.82      0.83       271
    disarment       0.76      0.55      0.64       263
          war       0.74      0.77      0.75       237

    micro avg       0.76      0.76      0.76      1998
    macro avg       0.76      0.76      0.75      1998
 weighted avg       0.76      0.76      0.75      1998

0.7557557557557557


In [144]:
from sklearn.gaussian_process import GaussianProcessClassifier
clf = GaussianProcessClassifier()
clf.fit(X_train,y_train)

GaussianProcessClassifier(copy_X_train=True, kernel=None,
             max_iter_predict=100, multi_class='one_vs_rest', n_jobs=None,
             n_restarts_optimizer=0, optimizer='fmin_l_bfgs_b',
             random_state=None, warm_start=False)

In [145]:
y_pred = clf.predict(X_test)

In [146]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[180  10   3  25   8  10   1  10]
 [ 16 183   8  15   3   4   2  21]
 [  5   1 200   2   2  13  18   0]
 [ 20  16   0 174   4  12   0  14]
 [ 19   2   0   6 203   9   0   8]
 [  6  10   7  11   0 217  13   7]
 [ 17  26  44  15   1   8 137  15]
 [ 17  13   1   8   4   1  11 182]]
               precision    recall  f1-score   support

   Assistance       0.64      0.73      0.68       247
  Negotiation       0.70      0.73      0.71       252
      Nuclear       0.76      0.83      0.79       241
        Peace       0.68      0.72      0.70       240
    Sanctions       0.90      0.82      0.86       247
consultations       0.79      0.80      0.80       271
    disarment       0.75      0.52      0.62       263
          war       0.71      0.77      0.74       237

    micro avg       0.74      0.74      0.74      1998
    macro avg       0.74      0.74      0.74      1998
 weighted avg       0.74      0.74      0.74      1998

0.7387387387387387


In [167]:
import xgboost as xgb
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 100, alpha = 10, n_estimators = 800)