In [1]:
import pandas as pd
spanishp = pd.read_csv("spanish.csv")

In [2]:
spanishp

symbol     jobno       dat language  \
0             A/56/1000  N0247012  20020711  Spanish   
1             A/56/1001  N0247395  20020710  Spanish   
2             A/56/1005  N0248380  20020723  Spanish   
3             A/56/1006  N0248399  20020717  Spanish   
4             A/56/1008  N0248716  20020719  Spanish   
5             A/56/1010  N0249043  20020722  Spanish   
6             A/56/1011  N0248954  20020722  Spanish   
7             A/56/1014  N0249919  20020726  Spanish   
8             A/56/1016  N0250334  20020731  Spanish   
9             A/56/1017  N0250351  20020731  Spanish   
10            A/56/1019  N0250766  20020802  Spanish   
11            A/56/1025  N0252194  20020814  Spanish   
12            A/56/1026  N0252770  20020815  Spanish   
13            A/56/1030  N0255201  20020828  Spanish   
14            A/56/1032  N0258042  20020905  Spanish   
15        A/56/47(SUPP)  N0243835  20020101  Spanish   
16             A/56/763  N0220070  20020103  Spanish   
17             A/56/773  N0221559  20020116  Spanish   
18             A/56/779  N0222649  20020123  Spanish   
19             A/56/790  N0222856  20020123  Spanish   
20             A/56/802  N0223956  20020201  Spanish   
21             A/56/806  N0224163  20020204  Spanish   
22             A/56/810  N0224378  20020206  Spanish   
23             A/56/813  N0224909  20020208  Spanish   
24             A/56/814  N0224755  20020208  Spanish   
25             A/56/815  N0224860  20020208  Spanish   
26             A/56/817  N0225008  20020212  Spanish   
27             A/56/819  N0225107  20020213  Spanish   
28             A/56/820  N0225328  20020214  Spanish   
29             A/56/822  N0225356  20020214  Spanish   
...                 ...       ...       ...      ...   
28759  S/RES/1359(2001)  N0143337  20010629  Spanish   
28760  S/RES/1363(2001)  N0147400  20010730  Spanish   
28761  S/RES/1364(2001)  N0147482  20010731  Spanish   
28762  S/RES/1369(2001)  N0153666  20010914  Spanish   
28763  S/RES/1370(2001)  N0154048  20010918  Spanish   
28764  S/RES/1372(2001)  N0155649  20010928  Spanish   
28765  S/RES/1374(2001)  N0159251  20011019  Spanish   
28766  S/RES/1375(2001)  N0160656  20011029  Spanish   
28767  S/RES/1376(2001)  N0163134  20011109  Spanish   
28768  S/RES/1378(2001)  N0163860  20011114  Spanish   
28769  S/RES/1379(2001)  N0165113  20011120  Spanish   
28770  S/RES/1380(2001)  N0166096  20011127  Spanish   
28771  S/RES/1382(2001)  N0166856  20011129  Spanish   
28772  S/RES/1383(2001)  N0168112  20011206  Spanish   
28773  S/RES/1384(2001)  N0169815  20011214  Spanish   
28774  S/RES/1385(2001)  N0170760  20011219  Spanish   
28775  S/RES/1386(2001)  N0170858  20011220  Spanish   
28776  ST/ADM/SER.B/409  N0160004  20011024  Spanish   
28777  ST/ADM/SER.B/569  N0120126  20010103  Spanish   
28778  ST/ADM/SER.B/570  N0121570  20010116  Spanish   
28779  ST/ADM/SER.B/572  N0126997  20010228  Spanish   
28780  ST/ADM/SER.B/573  N0130995  20010328  Spanish   
28781  ST/ADM/SER.B/575  N0136622  20010508  Spanish   
28782  ST/ADM/SER.B/576  N0140756  20010608  Spanish   
28783  ST/ADM/SER.B/577  N0146287  20010719  Spanish   
28784  ST/ADM/SER.B/578  N0151580  20010820  Spanish   
28785  ST/ADM/SER.B/579  N0154190  20010919  English   
28786  ST/ADM/SER.B/580  N0158072  20011015  Spanish   
28787  ST/ADM/SER.B/581  N0163747  20011114  Spanish   
28788  ST/ADM/SER.B/583  N0170235  20011218  Spanish   

                                                keywords       Category  \
0      ['INTERIM GOVERNMENTS', 'INTERNAL SECURITY', '...     Assistance   
1      ['BORDER INCIDENTS', 'ARMED INCIDENTS', 'ISRAE...            War   
2      ['CONSULTATIONS', 'REPORT PREPARATION', 'GUIDE...  Consultations   
3      ['ARMED INCIDENTS', 'BOMBINGS', 'ISRAEL', 'TER...            War   
4      ['BOMBINGS', 'ARMED INCIDENTS', 'TEL AVIV-JAFF...            War   
5      ['MILITARY PERSONNEL', 'TURKEY', 'CYPRUS', 'CY...    Negotiation   
6      ['PEACEKEEPI

In [5]:
data1 = spanishp[spanishp.Category == 'Assistance']
data1 = data1[1:1000]
data2 = spanishp[spanishp.Category == 'Consultations']
data2 = data2[1:1000]
data3 = spanishp[spanishp.Category == 'Disarment']
data3 = data3[1:1000]
data4 = spanishp[spanishp.Category == 'Negotiation']
data4 = data4[1:1000]
data5 = spanishp[spanishp.Category == 'Nuclear']
data5 = data5[1:1000]
data6 = spanishp[spanishp.Category == 'Peace']
data6 = data6[1:1000]
data7 = spanishp[spanishp.Category == 'Sanctions']
data7 = data7[1:1000]
data8 = spanishp[spanishp.Category == 'War']
data8 = data8[1:1000]

In [6]:
frames = [data1,data2,data3,data4,data5,data6,data7,data8]
spanishp = pd.concat(frames)

spanishp

symbol     jobno       dat language  \
10             A/56/1019  N0250766  20020802  Spanish   
56              A/56/875  N0228923  20020318  Spanish   
132   A/56/3/REV.1(SUPP)  N0246025  20020101  Spanish   
165             A/57/130  N0245970  20020705  Spanish   
166             A/57/136  N0246014  20020702  Spanish   
171             A/57/174  N0247427  20020702  Spanish   
173             A/57/180  N0246988  20020702  Spanish   
176         A/57/1(SUPP)  N0255180  20020828  Spanish   
177             A/57/203  N0247586  20020711  Spanish   
190             A/57/256  N0249704  20020724  Spanish   
194             A/57/268  N0250680  20020802  Spanish   
203             A/57/301  N0252161  20020812  Spanish   
206             A/57/320  N0252993  20020816  Spanish   
207             A/57/325  N0253276  20020820  Spanish   
211             A/57/338  N0253553  20020822  Spanish   
214             A/57/353  N0254126  20020827  Spanish   
218             A/57/377  N0257856  20020927  Spanish   
227       A/57/3(PARTII)  N0261453  20021001  Spanish   
230             A/57/410  N0259357  20020917  Spanish   
245             A/57/451  N0262356  20021007  Spanish   
247             A/57/455  N0262482  20021008  Spanish   
252             A/57/487  N0265109  20021021  Spanish   
276             A/57/520  N0270288  20021120  Spanish   
288             A/57/551  N0272393  20021204  Spanish   
289             A/57/552  N0270716  20021122  Spanish   
295             A/57/568  N0268190  20021107  Spanish   
299             A/57/578  N0266735  20021029  Spanish   
302             A/57/583  N0267440  20021101  Spanish   
311             A/57/613  N0269465  20021114  Spanish   
314             A/57/621  N0270436  20021129  Spanish   
...                  ...       ...       ...      ...   
4815            A/59/802  N0534330  20050512  Spanish   
4816            A/59/805  N0535095  20050519  Spanish   
4817            A/59/809  N0535670  20050524  Spanish   
4818            A/59/810  N0535658  20050524  Spanish   
4819            A/59/817  N0536447  20050527  Spanish   
4821            A/59/829  N0537705  20050608  Spanish   
4835            A/59/854  N0539638  20050623  Spanish   
4838            A/59/858  N0540427  20050630  Spanish   
4839            A/59/859  N0540504  20050630  Spanish   
4841            A/59/873  N0542232  20050608  Spanish   
4846            A/59/902  N0547372  20050829  Spanish   
4902            A/60/132  N0543114  20050719  Spanish   
4911            A/60/185  N0545075  20050802  Spanish   
4938            A/60/332  N0548118  20050906  Spanish   
4952            A/60/382  N0552572  20050928  Spanish   
4953            A/60/385  N0552735  20050928  Spanish   
4967            A/60/435  N0555677  20051017  Spanish   
4974            A/60/448  N0557528  20051027  Spanish   
4987            A/60/467  N0560267  20051111  Spanish   
4991            A/60/473  N0559852  20051117  Spanish   
5001        A/60/4(SUPP)  N0546839  20050822  Spanish   
5013            A/60/549  N0559923  20051110  Spanish   
5018            A/60/563  N0561476  20051122  Spanish   
5020            A/60/580  N0562822  20051205  Spanish   
5021            A/60/581  N0562828  20051205  Spanish   
5023            A/60/587  N0563694  20051212  Spanish   
5025            A/60/590  N0564365  20051215  Spanish   
5042            A/60/638  N0566615  20051228  Spanish   
5043            A/60/639  N0566621  20051228  Spanish   
5092          A/60/PV.61  N0563251  20050101  Spanish   

                                               keywords    Category  \
10    ['ARMED INCIDENTS', 'GAZA STRIP (STATE OF PALE...  Assistance   
56    ['INTERIM GOVERNMENTS', 'POST-CONFLICT RECONST...  Assistance   
132   ['DECLARATIONS (TEXT)', 'SOCIAL DEVELOPMENT', ...  Assistance   
165   ['HUMANITARIAN ASSISTANCE', 'ECONOMIC ASSISTAN...  Assistance   
166   ['PEACEBUILDING', 'ECONOMIC CONDITIONS', 'POST...  Assistance   
171   ['HUMANITARIAN ASSISTANCE', 'HUMAN RIGHTS', 'R...  

In [5]:
data1 = spanishp[spanishp.Category == 'Assistance']
data1 = data1[0:10]
data2 = spanishp[spanishp.Category == 'Consultations']
data2 = data2[0:10]
data3 = spanishp[spanishp.Category == 'Disarment']
data3 = data3[0:10]
data4 = spanishp[spanishp.Category == 'Negotiation']
data4 = data4[0:10]
data5 = spanishp[spanishp.Category == 'Nuclear']
data5 = data5[0:10]
data6 = spanishp[spanishp.Category == 'Peace']
data6 = data6[0:10]
data7 = spanishp[spanishp.Category == 'Sanctions']
data7 = data7[0:10]
data8 = spanishp[spanishp.Category == 'War']
data8 = data8[0:10]
frames2 = [data1,data2,data3,data4,data5,data6,data7,data8]
spanishmostra = pd.concat(frames2)

spanishmostra.to_csv("subset_spanish.csv")
len(spanishmostra)

80

In [11]:
subset_spa = spanishmostra.symbol
subset_spa.to_csv("subset_jobno.csv", header=False)

In [4]:
spanishp = pd.read_csv("spanishp.csv")

In [22]:
spanishp.groupby('Category')[['jobno']].count()

jobno
Category            
Assistance       999
Consultations    999
Disarment        999
Negotiation      999
Nuclear          999
Peace            999
Sanctions        999
War              999

In [23]:
spanishp.groupby('Category')[['jobno']].count()
s = pd.Series(range(len(spanishp)))
spanishp.set_index(s,inplace=True,append = True)

In [3]:
import pandas as pd
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

In [9]:
X = spanishp.text
y = spanishp.Category
y

0       Assistance
1       Assistance
2       Assistance
3       Assistance
4       Assistance
5       Assistance
6       Assistance
7       Assistance
8       Assistance
9       Assistance
10      Assistance
11      Assistance
12      Assistance
13      Assistance
14      Assistance
15      Assistance
16      Assistance
17      Assistance
18      Assistance
19      Assistance
20      Assistance
21      Assistance
22      Assistance
23      Assistance
24      Assistance
25      Assistance
26      Assistance
27      Assistance
28      Assistance
29      Assistance
           ...    
7962           War
7963           War
7964           War
7965           War
7966           War
7967           War
7968           War
7969           War
7970           War
7971           War
7972           War
7973           War
7974           War
7975           War
7976           War
7977           War
7978           War
7979           War
7980           War
7981           War
7982           War
7983        

In [26]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 10000000)
pd.set_option('display.width', 1000)

In [27]:
documents = []


#stoplist = set('for a of the and to in to be which some is at that we i who whom show via may my our might as well'.split())
stemmer = SnowballStemmer(language='spanish')

for i in range(len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[i]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.stem(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)
    pickle.dump( documents, open( 'texts_spanish_stem.p', "wb" ) )

In [4]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
import pickle
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
documents = pickle.load(open('texts_spanish_stem.p', 'rb'))
import json 

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('spanish'))
X = vectorizer.fit_transform(documents).toarray()
gtspa = vectorizer.get_feature_names()
with open ("get_spa.json","w",encoding="utf8")as f: json.dump(gtspa, f)

In [14]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [15]:
from sklearn.model_selection import train_test_split
X = pd.DataFrame(X)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=21)

In [16]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=100, n_estimators=600, max_features=320) 
classifier.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=100, max_features=320, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=600, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [17]:
y_pred = classifier.predict(X_test)


In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[265   4   2   9   0   7   5   5]
 [ 17 228  24  14   7  12  14   6]
 [ 31  17 190  12  34  14   3  16]
 [ 25   7   8 231   8   9   2  10]
 [  8   4  17   4 254   0   6   3]
 [ 20  16   1  11   0 239   5   3]
 [ 10   6   0   5   2   3 259   2]
 [ 19   4  16  17  12   5   7 204]]
               precision    recall  f1-score   support

   Assistance       0.67      0.89      0.77       297
Consultations       0.80      0.71      0.75       322
    Disarment       0.74      0.60      0.66       317
  Negotiation       0.76      0.77      0.77       300
      Nuclear       0.80      0.86      0.83       296
        Peace       0.83      0.81      0.82       295
    Sanctions       0.86      0.90      0.88       287
          War       0.82      0.72      0.77       284

    micro avg       0.78      0.78      0.78      2398
    macro avg       0.78      0.78      0.78      2398
 weighted avg       0.78      0.78      0.78      2398

0.7798165137614679


In [18]:
with open('classifier', 'wb') as picklefile:
    pickle.dump(classifier,picklefile)

In [24]:
#russian_metrics = confusion_matrix(y_test,y_pred)
spanish_metrics = classification_report(y_test,y_pred,output_dict=True)
#russian_metrics = accuracy_score(y_test, y_pred)
spa = pd.DataFrame(spanish_metrics).transpose()
spa.to_csv("spa_metrics.csv")

In [27]:
spanishp['prev_id'] = spanishp.index
y_test_db = pd.DataFrame(y_test)
y_test_db['id'] = range(len(y_test_db.index))
y_test_db['prev_id'] = y_test_db.index
y_pred_db = pd.DataFrame(y_pred)
y_pred_db['id'] = range(len(y_pred_db.index))
testvspred = pd.merge(y_test_db, y_pred_db, on='id', how='inner')
testspanish = pd.merge(spanishp, testvspred , on='prev_id', how='inner')
testspanish.to_csv("test_spanish.csv")